In [45]:
root='/content/drive/MyDrive/Colab Notebooks'

In [46]:
import os 
os.chdir(root)

In [47]:
assert root==os.getcwd()

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
plt.style.use('fivethirtyeight')
import joblib

#Basic Perceptron#

In [61]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.eta=eta
    self.epochs=epochs
    self.weights=np.random.randn(3)*1e-4
  def activation_function(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)
  def fit(self,X,Y):
    self.X=X
    self.Y=Y
    x_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch: {epoch}")
      print("--"*10)
      y_hat=self.activation_function(x_with_bias,self.weights)
      print(f"predicted value after forward pass: \n{y_hat}")
      self.error=self.Y-y_hat
      print(f"error: \n{self.error}")
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      self.weights=self.weights+self.eta*np.dot(x_with_bias.T,self.error)
      print(f"updated weights after epoch:\n{epoch}/{self.epochs} : \n{self.weights}")
      print("#####"*10)
  def predict(self,X):
      X_with_bias=np.c_[X,-np.ones((len(X),1))]
      return self.activation_function(X_with_bias,self.weights) 

  def total_loss(self):
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      return total_loss




In [62]:
def prepare_data(data):
  x=data.drop('y',axis=1)
  y=data['y']
  return x,y

In [63]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1],
}

df = pd.DataFrame(AND)

In [64]:
x,y = prepare_data(df)
ETA = 0.3
EPOCHS = 10
model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(x, y)
_ = model.total_loss()

--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[0 0 1 0]
error: 
0    0
1    0
2   -1
3    1
Name: y, dtype: int64
total loss: 0
updated weights after epoch:
0/10 : 
[1.26531496e-04 2.99915141e-01 6.56664389e-05]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
total loss: -2
updated weights after epoch:
1/10 : 
[-2.99873469e-01 -8.48588073e-05  6.00065666e-01]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
total loss: 1
updated weights after epoch:
2/10 : 
[1.26531496e-04 2.99915141e-01 3.00065666e-01]
##################################################
--------------------
for epoch: 3
--------------------
predicted valu

#Perceptron without Bias#
The total loss couldn't merge to zero even after tuning the epochs.


In [65]:
class Perceptron_without_bias:
  def __init__(self,eta,epochs):
    self.eta=eta
    self.epochs=epochs
    self.weights=np.random.randn(2)*1e-4
  def activation_function(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)
  def fit(self,X,Y):
    self.X=X
    self.Y=Y
    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch: {epoch}")
      print("--"*10)
      y_hat=self.activation_function(self.X,self.weights)
      self.error=self.Y-y_hat
      print(f"predicted value after forward pass: \n{y_hat}")
      self.weights=self.weights+self.eta*np.dot(self.X.T,self.error)
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      print(f"updated weights after epoch:\n{epoch}/{self.epochs} : \n{self.weights}")
      print("#####"*10)
  def predict(self,X):
    return self.activation_function(X,self.weights)
  def total_loss(self):
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      return total_loss

In [66]:
model = Perceptron_without_bias(eta=ETA, epochs=10)
model.fit(x, y)
_ = model.total_loss()

--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[0 0 1 1]
total loss: -1
updated weights after epoch:
0/10 : 
[-2.99884738e-01 -1.09382724e-05]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
total loss: 1
updated weights after epoch:
1/10 : 
[1.15262411e-04 2.99989062e-01]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 1 1 1]
total loss: -2
updated weights after epoch:
2/10 : 
[-2.99884738e-01 -1.09382724e-05]
##################################################
--------------------
for epoch: 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
total loss: 1
updated weights after epoch:
3/10 : 
[1.15262411e-04 2.99989062e-01]
##################################################
--------------------
for epoch: 4
----------------

#Perceptron with activation function as Sigmoid#
Total loss couldn't merge to zero.

In [67]:
class Perceptron_with_sigmoid:
  def __init__(self,eta,epochs):
    self.eta=eta
    self.epochs=epochs
    self.weights=np.random.randn(3)*1e-4
  def activation_function(self,inputs,weights):
    z=np.dot(inputs,weights)
    res= 1/(1+np.exp(-z))
    return np.where(res>0,1,0)
  def fit(self,X,Y):
    self.X=X
    self.Y=Y
    x_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch: {epoch}")
      print("--"*10)
      y_hat=self.activation_function(x_with_bias,self.weights)
      print(f"predicted value after forward pass: \n{y_hat}")
      self.error=self.Y-y_hat
      print(f"error: \n{self.error}")
      self.weights=self.weights+self.eta*np.dot(x_with_bias.T,self.error)
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      print(f"updated weights after epoch:\n{epoch}/{self.epochs} : \n{self.weights}")
      print("#####"*10)
  def predict(self,X):
      X_with_bias=np.c_[X,-np.ones((len(X),1))]
      return self.activation_function(X_with_bias,self.weights) 

  def total_loss(self):
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      return total_loss


In [68]:
model = Perceptron_with_sigmoid(eta=ETA, epochs=15)
model.fit(x, y)
_ = model.total_loss()

--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
total loss: -3
updated weights after epoch:
0/15 : 
[-0.30000862 -0.30008894  0.8999577 ]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
total loss: -3
updated weights after epoch:
1/15 : 
[-0.60000862 -0.60008894  1.7999577 ]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
total loss: -3
updated weights after epoch:
2/15 : 
[-0.90000862 -0.90008894  2.6999577 ]
##################################################
--------------------
for epoch: 3
--------------------
predicted value after forward pass: 
[1 1 

#Doubling the Number of Epochs#
once the total loss reaches 0 the weights aren't updated for the rest of the epochs

In [69]:
model = Perceptron(eta=ETA, epochs=20)
model.fit(x, y)
_ = model.total_loss()


--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
total loss: -3
updated weights after epoch:
0/20 : 
[-0.30002986 -0.2999338   0.89985824]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
total loss: 1
updated weights after epoch:
1/20 : 
[-2.98614400e-05  6.61997533e-05  5.99858244e-01]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
total loss: 1
updated weights after epoch:
2/20 : 
[0.29997014 0.3000662  0.29985824]
##################################################
--------------------
for epoch: 3
--------------------
predicted value after forward pass:

#Lowering the Number of Epochs#
couldn't reach the minimum loss

In [70]:
model = Perceptron(eta=ETA, epochs=3)
model.fit(x, y)
_ = model.total_loss()

--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
total loss: -3
updated weights after epoch:
0/3 : 
[-0.30001196 -0.29996931  0.8999006 ]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
total loss: 1
updated weights after epoch:
1/3 : 
[-1.19605024e-05  3.06858258e-05  5.99900597e-01]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
total loss: 1
updated weights after epoch:
2/3 : 
[0.29998804 0.30003069 0.2999006 ]
##################################################
total loss: 1


#Perceptron with Early Stopping#

In [71]:
class Perceptron_with_early_stopping:
  def __init__(self,eta,epochs):
    self.eta=eta
    self.epochs=epochs
    self.weights=np.random.randn(3)*1e-4
  def activation_function(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)
  def fit(self,X,Y):
    self.X=X
    self.Y=Y
    x_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch: {epoch}")
      print("--"*10)
      y_hat=self.activation_function(x_with_bias,self.weights)
      print(f"predicted value after forward pass: \n{y_hat}")
      self.error=self.Y-y_hat
      print(f"error: \n{self.error}")
      if(np.sum(self.error)==0):
        print("reached 100 percent accuracy stopping the training")
        break
      self.weights=self.weights+self.eta*np.dot(x_with_bias.T,self.error)
      print(f"updated weights after epoch:\n{epoch}/{self.epochs} : \n{self.weights}")
      print("#####"*10)
  def predict(self,X):
      X_with_bias=np.c_[X,-np.ones((len(X),1))]
      return self.activation_function(X_with_bias,self.weights) 

  def total_loss(self):
      total_loss=np.sum(self.error)
      print(f"total loss: {total_loss}")
      return total_loss

In [72]:
model = Perceptron_with_early_stopping(eta=ETA, epochs=20)
model.fit(x, y)
_ = model.total_loss()


--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:
0/20 : 
[ 0.2998855   0.29996909 -0.29999099]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:
1/20 : 
[-1.14503591e-04 -3.09105233e-05  6.00009013e-01]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:
2/20 : 
[0.2998855  0.29996909 0.30000901]
##################################################
--------------------
for epoch: 3
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3 